# config.yml —— 所有配置集中于此
uuid: "11453d43-607c-4396-929a-699247d096ad"     #输入uuid
tuic_port: "40009"                  #输入端口=确认部署
hy2_port: "40152"                   #输入端口=确认部署
reality_port: "40009"               #输入端口=确认部署
sni: "www.bing.com"

